=== zhao1jin4/eclipse_java_workspace/eclipse_java_workspace/J_JavaSE/src/xml/schema/dataType.xsd
<?xml version="1.0"  encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://zhaojin.org/dataType" elementFormDefault="qualified">
	<!--elementFormDefault="qualified" 指出任何 XML 实例文档所使用的且在此 schema 中声明过的元素必须被命名空间限定。 -->

	<xs:attribute name="lang" type="xs:string" default="EN" />

	<xs:complexType name="personinfo">
		<xs:sequence>
			<xs:element name="firstname" type="xs:string" />
			<xs:element name="lastname" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="fullpersoninfo">
		<xs:complexContent>
			<xs:extension base="personinfo">
				<xs:sequence>
					<xs:element name="address" type="xs:string" />
					<xs:element name="city" type="xs:string" />
					<xs:element name="country" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="carType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Audi" />
			<xs:enumeration value="Golf" />
			<xs:enumeration value="BMW" />
		</xs:restriction>
	</xs:simpleType>


	<xs:group name="mypersongroup"><!-- 必须在 group 声明内部定义一个 all、choice 或者 sequence 元素 -->
		<xs:sequence>
			<xs:element name="firstname" type="xs:string" />
			<xs:element name="lastname" type="xs:string" />
			<xs:element name="birthday" type="xs:date" />
		</xs:sequence>
	</xs:group>
	<xs:complexType name="mypersoninfo">
		<xs:sequence>
			<xs:group ref="mypersongroup" />
			<xs:element name="country" type="xs:string" />
		</xs:sequence>
	</xs:complexType>


	<xs:attributeGroup name="personattrgroup">
		<xs:attribute name="firstname" type="xs:string" />
		<xs:attribute name="lastname" type="xs:string" />
		<xs:attribute name="birthday" type="xs:date" />
	</xs:attributeGroup>

	<!-- 上 面的在 eclipse中没有验证, -->





	<xs:element name="dataType">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="lastname" type="xs:string" />
				<xs:element name="families" type="xs:integer" />
				<xs:element name="dateborn" type="xs:date" />
				<xs:element name="isGraduated" type="xs:boolean" />
				<xs:element name="workBeginTime" type="xs:time" />
				<xs:element name="loginDateTime" type="xs:dateTime" />
				<xs:element name="salary" type="xs:decimal" />
				<xs:element name="password">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="5" />
							<xs:maxLength value="8" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="age">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0" />
							<xs:maxInclusive value="120" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="email">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]{2|3}" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="gender">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="male|female" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="product">
					<xs:complexType>
						<xs:attribute name="prodid" type="xs:positiveInteger"
							fixed="22" />
						<xs:attribute name="prodname" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>

				<xs:element name="letter">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="orderid" type="xs:positiveInteger" />
							<xs:element name="shipdate" type="xs:date" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="person">
					<xs:complexType>
						<xs:all> <!-- <all> 指示器规定子元素可以按照任意顺序出现，且每个子元素必须只出现一次： -->
							<xs:element name="firstname" type="xs:string" />
							<xs:element name="lastname" type="xs:string" />
						</xs:all>
					</xs:complexType>
				</xs:element>

				<xs:element name="personType">
					<xs:complexType>
						<xs:choice> <!-- <choice> 只可出现其中一种,并一次 -->
							<xs:element name="employee" type="xs:string" />
							<xs:element name="manager" type="xs:string" />
						</xs:choice>
					</xs:complexType>
				</xs:element>

				<xs:element name="workProject">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="project" type="xs:string" minOccurs="1"
								maxOccurs="3" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>









				<!-- 下面的在 eclipse有验证,但是不在文本上提示,在右边提示 -->



				<xs:element name="shoesize">
					<xs:complexType>
						<xs:simpleContent>	<!-- 简易的内容（文本和属性），因此我们要向此内容添加 simpleContent 元素 -->
							<xs:extension base="xs:integer">
								<xs:attribute name="country" type="xs:string" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>


				<!-- 下 面的在 eclipse中没有验证, -->


				<xs:element name="car" type="carType" />
				<xs:element name="techer" type="fullpersoninfo" />
				<xs:element name="neighbor" type="personinfo" />



				<xs:element name="childPeple" type="mypersoninfo" />



				<xs:element name="person123">
					<xs:complexType>
						<!-- <xs:attributeGroup ref="personattrgroup" /> 报错??? -->
					</xs:complexType>
				</xs:element>

				<xs:element name="workExperence">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="company" type="xs:string" />
							<xs:any minOccurs="0" maxOccurs="unbounded" /> <!-- 只可有一个any -->
						</xs:sequence>
						<!--<xs:anyAttribute /> 只可有一个anyAttribute -->
					</xs:complexType>
				</xs:element>

				<xs:element name="myAnyAttribute">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="company" type="xs:string" />
						</xs:sequence>
						<xs:anyAttribute /> <!--只可有一个anyAttribute -->
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== zhao1jin4/eclipse_java_workspace/eclipse_java_workspace/J_JavaSE/src/xml/schema/dataType.xml
<?xml version="1.0"  encoding="UTF-8"?>
<dataType xmlns="http://zhaojin.org/dataType" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://zhaojin.org/dataType   dataType.xsd"><!-- {namespace} {location} -->
	<lastname>aa</lastname>
	<families>5</families>
	<dateborn>2012-02-20</dateborn>
	<isGraduated>true</isGraduated>
	<workBeginTime>17:02:39</workBeginTime>
	<loginDateTime>2012-02-20T17:02:39</loginDateTime>
	<salary>5000.3</salary>
	<password>156456</password>
	<age>23</age>
	<email>asdf@aa.com</email>
	<gender>male</gender>
	
	<product prodid="22" prodname="testname" />
	
	<letter>
		adfsa<name>aaa</name>asdf
		asdf<orderid>23</orderid>asdf
		asdf<shipdate>2012-02-20</shipdate>asdf
	</letter>
	<person>
		<lastname></lastname>
		<firstname></firstname>
	</person>
	<personType>
		<employee></employee>
	</personType>

	<workProject>
		<project></project>
		<project></project>
		<project></project>
	</workProject>




	<!-- 下面的在 eclipse有验证,但是不在文本上提示,在右边提示 -->
	<shoesize country="aa">123</shoesize>

	<!-- 下面的在 eclipse中没有验证, -->
	
	<car>sadf</car> 
	
	<techer>
	</techer>
	<neighbor>
	</neighbor>
	
	

	<childPeple>
	</childPeple>
	
	<person123></person123>
	
	<workExperence >
		<company></company>
		<abc></abc>
		<a></a>
	</workExperence>
	
	
	<myAnyAttribute > <!-- a="1" b="2"  报错???? -->
		<company  ></company>
	</myAnyAttribute>
	
	
</dataType>
